---
- name: installs fail2ban on ansible hosts
  hosts: web-servers
  become: yes
  become_user: root
  tasks:
    - name: install apt fail2ban packages
      apt:
        name: ['fail2ban', 'sendmail']
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: override the basic fail2ban configuration with .local file
      copy:
        src: fail2ban/jail.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: 0644